apiVersion: v1
kind: ConfigMap
metadata:
  name: exercises-config
  labels:
    app: exercises
data:
  application.json: |
    {
       "verticles":{
          "http":{
             "options":{
                "config":{
                   "oauth2":{
                      "clientSecret":"0564f7a2-05df-4cf9-bb85-bd4058283553"
                   }
                }
             }
          }
       }
    }