apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercises-deployment
  labels:
    app: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exercises
  template:
    metadata:
      labels:
        app: exercises
    spec:
      containers:
      - name: exercises
        image: jpiecuch/exercises:1.0
        imagePullPolicy: Always
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        ports:
        - containerPort: 8086
        env:
          - name: SPRING_CLOUD_CONFIG_URI
            value: http://config-service:8081
          - name: ACTIVE_PROFILE
            value: k8s
          - name: VERTX_CONFIG_PATH
            value: /etc/config/application.json
      volumes:
        - name: config-volume
          secret:
            secretName: exercises-secrets
            items:
              - key: application.json
                path: application.json